# Generated by Django 2.2 on 2019-05-11 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_valid', models.BooleanField(default=True, verbose_name='是否有效')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否已删除')),
                ('code', models.CharField(max_length=5, unique=True, verbose_name='学院编号')),
                ('name', models.CharField(max_length=50, verbose_name='学院名称')),
                ('abbr_name', models.CharField(max_length=20, null=True, verbose_name='学院简称')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_valid', models.BooleanField(default=True, verbose_name='是否有效')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否已删除')),
                ('tid', models.CharField(max_length=15, unique=True, verbose_name='教师编号')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('worktype', models.CharField(max_length=1, verbose_name='职工类别')),
                ('phone', models.CharField(max_length=15, null=True, unique=True, verbose_name='电话号码')),
                ('college', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='teacher.CollegeInfo', verbose_name='学院')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
