# Generated by Django 2.2 on 2019-05-11 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseBaseInfo',
            fields=[
                ('is_valid', models.BooleanField(default=True, verbose_name='是否有效')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否已删除')),
                ('cid', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='课程号')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='课程名称')),
                ('course_prop', models.CharField(help_text='必修/限选/任选/校选', max_length=2, null=True, verbose_name='课程性质')),
                ('credit', models.FloatField(verbose_name='学分')),
                ('study_hourse', models.FloatField(default=0, verbose_name='总学时')),
                ('collegeid', models.CharField(max_length=5, null=True, verbose_name='学院id')),
                ('college', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='teacher.CollegeInfo', verbose_name='管理单位')),
                ('cteacher', models.ManyToManyField(to='teacher.Teacher', verbose_name='开课老师')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
