# Generated by Django 2.2 on 2019-05-11 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ccode', models.CharField(max_length=5, unique=True, verbose_name='教室编号')),
                ('capacity', models.CharField(max_length=3, verbose_name='教室容量')),
            ],
        ),
        migrations.CreateModel(
            name='CourseTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_valid', models.BooleanField(default=True, verbose_name='是否有效')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否已删除')),
                ('workday', models.CharField(max_length=6, verbose_name='上课时间')),
                ('time', models.CharField(max_length=25, verbose_name='上课具体时间')),
                ('cclass', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='student.ClassInfo', verbose_name='班级')),
                ('cgrade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='student.GradeInfo', verbose_name='开课年级')),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='course.CourseBaseInfo', verbose_name='课程编号')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='arrange.ClassroomInfo', verbose_name='教室')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourseArrange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_valid', models.BooleanField(default=True, verbose_name='是否有效')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否已删除')),
                ('cclass', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='student.ClassInfo', verbose_name='对应班级')),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='course.CourseBaseInfo', verbose_name='课程编号')),
                ('cmajor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='student.MajorInfo', verbose_name='对应专业')),
                ('cname', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coursearrange_coursebaseinfo', to='course.CourseBaseInfo', verbose_name='课程名称')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
