# Generated by Django 2.2 on 2019-05-11 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassInfo',
            fields=[
                ('clid', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='班级编号')),
            ],
        ),
        migrations.CreateModel(
            name='GradeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=4, verbose_name='年级')),
            ],
        ),
        migrations.CreateModel(
            name='MajorInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.CharField(max_length=5, verbose_name='专业编号')),
                ('mname', models.CharField(max_length=50, null=True, verbose_name='专业名称')),
                ('mcollege', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teacher.CollegeInfo', verbose_name='开设学院')),
            ],
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('is_valid', models.BooleanField(default=True, verbose_name='是否有效')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否已删除')),
                ('sid', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='学号')),
                ('sname', models.CharField(max_length=50, verbose_name='学生姓名')),
                ('scomment', models.CharField(max_length=128, null=True, verbose_name='备注')),
                ('sclass', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='student.ClassInfo', verbose_name='学生所属班级')),
                ('scollege', models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.PROTECT, to='teacher.CollegeInfo', verbose_name='学生所属学院')),
                ('sgrade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='student.GradeInfo', verbose_name='学生所属年级')),
                ('smajor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='student.MajorInfo', verbose_name='学生专业')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='classinfo',
            name='clgrade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='student.GradeInfo', verbose_name='年级'),
        ),
        migrations.AddField(
            model_name='classinfo',
            name='clmajor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='student.MajorInfo', verbose_name='专业'),
        ),
    ]
